#!/usr/bin/env bash

function indent {
  echo "         $*"
}

function new_service {
  local nm_runit="$1"; shift
  local nm_block="${nm_runit%%.*}"
  local nm_service="${nm_runit#*.}"

  local nm_block_home="_${nm_block//-/_}_home"
  if [[ ! -x "${!nm_block_home}/script/server" ]]; then
    return 0
  fi

  echo "-----> Creating runit service $nm_service"

  if [[ "$nm_service" == "$nm_block" ]]; then
    nm_service='default'
  fi

  local pth_service="${BUILD_DIR}/sv/${nm_runit}" 

  mkdir -p "${pth_service}"
  mkdir -p "${pth_service}/env"

  mkdir -p "${pth_service}/log"
  cat <<"__EOF" >"${pth_service}/log/run" 
#!/usr/bin/env bash
exec 2>&1
source "$HOME/.bashrc"
exec envdir ../env svlogd -tt .
__EOF
  chmod 755 "${pth_service}/log/run"

  cat <<"__EOF" | env nm_service="$nm_service" envsubst '$nm_service' > "${pth_service}/run"
#!/usr/bin/env bash
runhome="$(cd -P -- "${BASH_SOURCE%/*}" && pwd -P)"
exec 2>&1
source "${HOME}/.bashrc"
exec envdir ./env "${runhome}/run.impl" "${nm_service}" "$@"
__EOF
  chmod 755 "${pth_service}/run"

  local nm_block_home="_${nm_block//-/_}_home"
  cat <<"__EOF" | env nm_block="$nm_block" envsubst '$nm_block' > "${pth_service}/run.impl"
#!/usr/bin/env bash
exec 2>&1
exec ${!nm_block_home}/script/server "$@"
__EOF
  chmod 755 "${pth_service}/run.impl"
}

function add_env {
  local nm_service="$1"; shift
  local nm_env="$1"; shift
  local val_env="$1"; shift

  echo "$val_env" > "${BUILD_DIR}/sv/${nm_service}/env/${nm_env}"
}

function read_services {
  cat "Blockfile.json" | jq -r '.run//{} | keys[]'
  cat "Blockfile.json.site" 2>/dev/null | jq -r '.run//{} | keys[]'
}

function main {
  local BUILD_DIR="$1"; shift
  local CACHE_DIR="$1"; shift
  local ENV_DIR="$1"; shift

  mkdir -p "$BUILD_DIR/sv"
  mkdir -p "$SVDIR"

  if [[ "$#" == 0 ]]; then
    read_services | while read -r a; do
      main $BUILD_DIR $CACHE_DIR $ENV_DIR "$a"
    done
    return 0
  fi

  local nm_service="$1"; shift
  new_service "$nm_service"
}

source sub "$0" "$@"
