#!/usr/bin/env bash

function home_bootstrap {
  local shome="${_defn_home_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  block compile bundler
}

home_bootstrap "$@"
