#!/usr/bin/env bash

function service_fresh {
  local shome="${_service_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  if [[ -x "$(which pleaserun 2>&- || true)" ]]; then
    return 0
  fi

  return 1
}

service_fresh "$@"
